---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: la-niranjan
  labels:
    app: hello
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: niranjan19/gitops:hellov1.2
